### ISSUE TITLE
Build fail for non-distro topics when files are not in branch

### ISSUE THREAD

**Issue by adellape** [redhataccess/ascii_binder#116]
Currently asciibinder fails on build when a directory or topic is not available in the repo, even if the `_topic_map.yaml` says the topic shouldn't appear in the distro being built.

For example:

```
- Name: Diagnostics Tool
  File: diagnostics_tool
  Distros: openshift-origin,openshift-enterprise
```

This topic should appear in Origin and OCP, but not OSD or Online. Then when building from a branch for the `openshift-dedicated` distro, fails with:

```
RuntimeError: In _topic_map.yml, could not find file diagnostics_tool under directory admin_guide for topic Diagnostics Tool in topic group Cluster Administration. at
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:412:in `validate_topic_item'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:443:in `block (2 levels) in validate_config'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:435:in `each'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:435:in `block in validate_config'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:432:in `each'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:432:in `validate_config'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:172:in `build_config'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:574:in `block in generate_docs'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:546:in `each'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/lib/ascii_binder/helpers.rb:546:in `generate_docs'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/bin/asciibinder:15:in `call_generate'
    /home/durant/.gem/ruby/gems/ascii_binder-0.1.8/bin/asciibinder:291:in `<top (required)>'
    /home/durant/bin/asciibinder:22:in `load'
    /home/durant/bin/asciibinder:22:in `<main>'.
```

Solution so far has been either remove the entry from `_topic_map.yaml` (for just that branch) or checkout the missing files from `master` or another branch just to make the build process happy, even tho it won't appear in the OSD doc. Not sure if there's a limitation that would prevent it, but, it would be nice if asciibinder could allow the build to complete if the files aren't there, if the topic map doesn't actually need it for that distro.

**Comment by nhr** [comment]
You are running ascii_binder 0.1.8. Please upgrade to the latest (0.1.13) and let me know if you are still hitting that error:

`gem update ascii_binder`
