### ISSUE TITLE
Page names of less than 3 characters are invalid

### ISSUE THREAD

**Issue by r0ckarong** [redhataccess/ascii_binder#50]
We have an element syntax that contains things like

"ki" "do" and "on" with respective pages in the documentation called for example "do.adoc". When I try to add these to the topic configuration I get an error message on build saying it's not a string.

````
  - Name: Do
     File: do
```

I've tried and the minimum is 3 characters both for Name and File. Can I change this or is this a limit needed for something else?

**Comment by nhr** [comment]
Can you please pastbin the error message?

**Comment by r0ckarong** [comment]
Found out the error actually comes from dir names being too short. Tried several things and 2 character filenames are no problem but it breaks with 2 char directories.

Short folder does not work (dir "no")
```
Name: AsciiBinder Doc Project
Dir: welcome
Topics:
  - Name: Welcome
    File: index
Name: Test1
Dir: no
Topics:
  - Name: If
    File: if
```

```
Building all distributions.
Error: Could not generate docs:
RuntimeError: One of the topic groups in _topic_map.yml is not using a string for the Dir setting; current value is false at
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:357:in `block in validate_topic_group'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:355:in `each'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:355:in `validate_topic_group'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:421:in `block in validate_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:420:in `each'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:420:in `validate_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:172:in `build_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:562:in `block in generate_docs'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:534:in `each'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:534:in `generate_docs'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/bin/asciibinder:15:in `call_generate'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/bin/asciibinder:291:in `<top (required)>'
    /usr/local/bin/asciibinder:23:in `load'
    /usr/local/bin/asciibinder:23:in `<main>'.
Try --help for help.
```

Short file works (dir "work")
```
Name: AsciiBinder Doc Project
Dir: welcome
Topics:
  - Name: Welcome
    File: index
Name: Test1
Dir: work
Topics:
  - Name: If it works
    File: if
```

```
Building all distributions.

WARNING: Branch 'master' includes the following .adoc files that are not referenced in the _topic_map.yml file:
- no/if
- welcome/index
- work/one

Building AsciiBinder Doc Project for branch 'master'
  - work/if

All builds completed.
```

**Comment by nhr** [comment]
If your `_topic_map.yml` file is exactly as you've pasted it, then it is missing record delimiters between topics. See https://github.com/openshift/openshift-docs/blob/master/_build_cfg.yml#L5 for an example. I mention this because if you are missing record delimiters then it is entirely possible that the value of 'Dir' is an array and not a string, depending on what the YAML parser tries to do.

**Comment by r0ckarong** [comment]
Just checked this. Same problem with explicit delimiter.

```
---
Name: AsciiBinder Doc Project
Dir: welcome
Topics:
  - Name: Welcome
    File: index
---
Name: Test1
Dir: no
Topics:
  - Name: If
    File: if
```

```
Building all distributions.
Error: Could not generate docs:
RuntimeError: One of the topic groups in _topic_map.yml is not using a string for the Dir setting; current value is false at
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:357:in `block in validate_topic_group'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:355:in `each'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:355:in `validate_topic_group'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:421:in `block in validate_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:420:in `each'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:420:in `validate_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:172:in `build_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:562:in `block in generate_docs'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:534:in `each'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:534:in `generate_docs'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/bin/asciibinder:15:in `call_generate'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/bin/asciibinder:291:in `<top (required)>'
    /usr/local/bin/asciibinder:23:in `load'
    /usr/local/bin/asciibinder:23:in `<main>'.
Try --help for help.
```

**Comment by nhr** [comment]
Ah. I see the problem. "no" is resolving to `false`.

**Comment by nhr** [comment]
The YAML parser is transforming the string 'no' to `false`. If you want it to remain a string, you need to put it in quotes.

**Comment by r0ckarong** [comment]
Good to know :) Thanks for the help.
